Sprint2
AnzhelikaSamchuk/BeautyWorld pull request #2
Opened 2021-10-24 17:25 UTC by AnzhelikaSamchuk

Что не смогла: 
- Текст становится прозрачный в тот момент, когда и девушка с кругом прозрачные, как сделать так, чтобы текст оставался таким же? Пробовала через rgb задавать прозрачность все-равно не получилось.
- При применении прозрачности круг перекрыл девушку, должно быть наоборот. Тоже не смогла исправить.
- При изменении размеров экрана блок с ссылками на инст, вк, youTube не остается по центру.

2021-11-16 03:43 UTC, studenttsu commented
> Текст становится прозрачный в тот момент, когда и девушка с кругом прозрачные, как сделать так, чтобы текст оставался таким же? Пробовала через rgb задавать прозрачность все-равно не получилось.

Нужно поднять z-index для hero__content, чтобы слой был выше над картинкой с девушкой.
![image](https://user-images.githubusercontent.com/12005449/141891677-29c15fcf-4430-4714-89bc-b09983a4152a.png)

> При применении прозрачности круг перекрыл девушку, должно быть наоборот. Тоже не смогла исправить.

Не совсем понял проблему, но в любом случае сам элемент круга можно расположить первый и тогда картинка будет выше по приоритету. Ну и можно поиграться с z-index
![image](https://user-images.githubusercontent.com/12005449/141891861-280f174f-42be-4fe4-8fd1-522625254b2f.png)

> При изменении размеров экрана блок с ссылками на инст, вк, youTube не остается по центру.

Посмотрел, вроде адекватно ведёт себя этот блок. Оставим как есть

2021-11-16 04:17 UTC, studenttsu requested changes
Отличный результат! Стоит дожать комменты, осталось немного)

2021-11-16 04:17 UTC, studenttsu commented on src/scss/style.scss
> +	//width: 255px;
Не стоит оставлять код на потом

2021-11-16 04:17 UTC, studenttsu commented on src/scss/style.scss
> +	&__title a:hover {
Можно перенести выше, будет

```SCSS
&__title {
  a {
    color: $color-blue;
    
     &:hover {
	color: darken($color-blue, 20%);
     }
  }
}
```

2021-11-16 04:17 UTC, studenttsu commented on src/scss/style.scss
> +	&::before {
Нужно не забывать задавать position

![image](https://user-images.githubusercontent.com/12005449/141904765-b5eb8cff-73d0-4e0f-ac68-b71f3d7194a7.png)

2021-11-16 04:17 UTC, studenttsu commented on src/index.html
> +							<div class="col-xl-6 col-lg-6 col-md-12 col-12">
`нужно поправить`

Стоит разобраться почему появились внутренние отступы, которых нет в макете и у последних элементов нужно убрать нижние отступы.

![image](https://user-images.githubusercontent.com/12005449/141907109-e8325ce1-e947-4762-a4c4-f4f4f645d38a.png)

Можно поступить так - каждому элементы задаём верхний отступ, а не нижний и потом компенсируем сверху отрицательным отступом у родителя

2021-11-17 10:47 UTC, AnzhelikaSamchuk commented on src/index.html
> +	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
Не получилось, когда стала удалять стили, все поплыло.

2021-11-18 02:46 UTC, studenttsu commented on src/index.html
> +	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
Нужно разобраться, пока предлагаю двигаться дальше

2021-11-18 02:47 UTC, studenttsu approved these changes
Отлично, работа принята!

2021-11-18 06:04 UTC, merged